---
title: 'Michael Stonebreaker: “La privacidad de los datos es un tema legal y no técnico”'
author: 'Marta Apablaza R'
date: 2020-01-07
categories: ['Datos']
tags: ['Michael Stonebreaker', 'BigData', 'ComputerScience', 'CienciasdelaComputación', 'Datos']
summary: 'El científico quien ayudó a crear la mayoría de las bases de datos relacionales reflexiona sobre datos y privacidad'
---

```{r setup, cache = FALSE, echo = FALSE, message = FALSE, warning = FALSE, tidy = FALSE}
knitr::opts_chunk$set(message = F, error = F, warning = F, cache = T, comment = NA, fig.align = "center", dpi = 100, fig.width = 6, fig.height = 5, tidy = F)
```

El científico quien ayudó a crear la mayoría de las bases de datos relacionales del mercado, reflexiona sobre la manera en que los datos son usados en el mundo empresarial al mismo tiempo que afirma que el uso y privacidad de los datos médicos de las personas es un tema que debe reflexionar la sociedad en conjunto y no sólo los cientistas de datos. 

“Una de las primeras cosas que le digo a cada empresa que conozco es que deben tener una estrategia de integración de datos”, indica Michael Stonebreaker, Premio Turing 2014 y creador del concepto “Big data” en un break del Heildelberg Laurate Forum. 

“Este consejo se lo digo incluso a compañías internacionales. Un ejemplo: La compañía de automóviles, Toyota Motor Europe, tiene una filial española, francesa, británica. Entonces, si una persona compra un automóvil en Toyota España y luego se muda a Francia, la compañía pierde esa información. Si la compañía quiere proveer un mejor servicio al cliente deberían integrar su base de datos de servicio al cliente”, indica Stonebreaker. Su estrategia es consolidar 250 base de datos en 40 idiomas. “Están en el proceso de hacer eso”. El problema de las grandes empresas no es integrar múltiples bases de datos sino también homologar los datos.

## Desafíos del Big Data: Modelo de predicción de demanda y precios óptimos

Según Stonebraker, un gran desafío que enfrenta el mercado y las empresas es la optimización de sus ingresos. “¿Cómo pueden utilizar las empresas, el “aprendizaje automático” o el “machine learning” para tener un mejor retorno de la inversión?”, se pregunta el científico. 

“Mi ejemplo favorito es en la industria hotelera de Estados Unidos. El precio de la habitación de cualquier hotel varía según la cantidad de habitaciones que tengan, y con cuánto tiempo de anticipación reserve el cliente. Si tienen muchas habitaciones sin vender, el precio baja. Entonces, ¿Qué te gustaría si fueras dueño de un hotel? Un modelo predictivo que predeciría cuál es el precio óptimo para cobrar por una habitación de hotel en una fecha determinada”, indica.

El experto, indica que el problema del Aprendizaje Automático y las empresas, es que a menudo recopilar los datos que necesitas es costoso y, a menos que haya suficiente valor en el modelo predictivo, no vale la pena hacerlo.

El aprendizaje automático o Machine Learning generalmente depende de una estrategia de integración de datos, y ese es otro problema de Big Data, las compañías se enfrentan a esto. Otro tópico que será interesante para el científico de la computación es de qué manera se utilizará los datos generados por el Internet de las Cosas. 

## Datos Médicos: el dilema que viene

Con todo, Michael Stonebreaker sostiene que en los próximos años uno de los grandes desafíos será la privacidad de los datos médicos de las personas. 

“El cuidado de la salud de las personas será un gran desafío para los profesionales relacionados con las bases de datos. Es decir, la construcción de una base de datos de exámenes médicos, consistente a la que el médico pueda recurrir a la hora de un tratamiento o diagnóstico”, indica. 

“Un médico puede nombrar un síntoma como dolor de pecho y otro, angustia. No hay una consistencia en la terminología”. 
Entonces, ¿Aconseja a los gobiernos de los países una estrategia coherente para los datos?

“Sí. Todo Servicio Nacional de Salud debería tener una estrategia coherente de datos porque la revisión del retorno de la inversión será gigantesca”, explica.

Entonces, ¿Qué pasa con la transparencia y la privacidad de los datos médicos? 

“La privacidad es un gran problema y en el momento en que tengamos un sistema como el que describí, los médicos podrán realizar consultas que indiquen quién más tiene este tipo de síntomas. Si el sistema permitiera aquella acción, las probabilidades de que el médico pueda identificar de manera única a personas con los mismos síntomas son muy altas”. 

“Creo que el beneficio propio de tener datos médicos y la privacidad de las personas son supuestos y la utilización de estos, es una decisión que depende de la sociedad. Mi apuesta, es que finalmente cada persona decidirá cómo utilizar sus datos. "Estoy dispuesto a compartir mis datos o no".

“Mi sensación es que la única forma de proteger nuestra privacidad, es que haya leyes al respecto. Técnicamente en este momento hay muchas organizaciones que saben mucho de ti. Entonces, creo que la respuesta a la privacidad en su mayoría es legal y no técnica”, finaliza.
