---
title: 'Epistemonikos: lo que hay que conocer sobre el COVID-19'
author: 'Marta Apablaza R'
date: 2020-04-07
categories: ['Datos']
tags: ['Epistemonikos', 'BigData', 'ComputerScience', 'CienciasdelaComputación', 'Datos']
summary: 'Epistemonikos, plataforma chilena que tiene por objetivo facilitar la toma de decisiones en instituciones de salud, ha tomado protagonismo en medio de la emergencia provocada por el avance de este virus'
---

```{r setup, cache = FALSE, echo = FALSE, message = FALSE, warning = FALSE, tidy = FALSE}
knitr::opts_chunk$set(message = F, error = F, warning = F, cache = T, comment = NA, fig.align = "center", dpi = 100, fig.width = 6, fig.height = 5, tidy = F)
```

Recopilar información científica para tomar decisiones de salud pública, pareciera ser una de los objetivos más importantes que los gobiernos de distintos países enfrentan en medio de la crisis sanitaria provocada por la propagación del COVID-19. 

En este contexto, Epistemonikos, plataforma chilena que tiene por objetivo facilitar la toma de decisiones en instituciones de salud, ha tomado protagonismo en medio de la emergencia provocada por el avance de este virus. 

Una pregunta, muchas respuestas

La historia de Epistemonikos comenzó hace algunos años atrás cuando Daniel Pérez, ingeniero de la Facultad de Ciencias Físicas y Matemáticas (FCFM), y Gabriel Rada, médico de la Universidad Católica, decidieron crear Epistemonikos. Esto, debido a que notaron la necesidad de los sistemas de salud públicos, además de la médica y científica, de contar con revisiones sistemáticas generalizadas.

“Ministerios, clínicas o doctores deben tomar decisiones basándose en la mejor evidencia científica existente. Como la tarea de buscar la mejor evidencia puede ser difícil y, generalmente toma entre uno y dos años y medio de trabajo, creamos Epistemonikos”, señaló  en 2016, Daniel Pérez. 

La premisa de Epistemonikos es buscar todos los estudios que se han hecho sobre cierto tema en salud y sintetizarlos a través de un método llamado meta análisis. De esta manera, Epistemonikos ha contribuido, por ejemplo, al debate del Timerosal en las vacunas.  

A través de los años, la Fundación ha podido  desarrollar diferentes herramientas y ha mejorado su base de datos, lo que les ha permitido recopilar más de 300 mil revisiones sistemáticas en el mundo de la salud.

Covid-19: lo que hay que conocer

En este tiempo de emergencia sanitaria, la síntesis de evidencia científica sobre el COVID-19 ha cobrado vital importancia en todo el mundo. En este contexto,  la Fundación Epistemonikos decidió dedicar el 100% de sus esfuerzos a la recopilación y síntesis de evidencia científica respecto al coronavirus. 

¿Se deben evitar los antiinflamatorios para tratar los síntomas de COVID-19? ¿Es efectivo el Interferón para el tratamiento de COVID-19? Son algunas de las preguntas para las cuales se está buscando respuesta. “Esto con el objetivo de llevar de forma fácil y oportuna la evidencia a quienes se encuentran en la posición de tomar decisiones con respecto al COVID-19, buscando también cumplir nuestra misión como organización”, indica Javiera Sepúlveda, Jefa de Comunicaciones y Alianzas Estratégicas de Epistemonikos. 

Y agrega: “Desde el inicio de la emergencia hemos unido fuerzas con varios equipos de expertos, formando nuestro L·OVE Working Group para trabajar en tres frentes: el primero es “L·OVE COVID-19”, una colección de evidencia "viviente" donde se encuentran todas las revisiones sistemáticas organizadas en temas y preguntas de investigación. Segundo es la creación de revisiones sistemáticas "vivientes" relativas a COVID-19, que van siendo actualizadas a medida que nueva evidencia cumple con los requisitos de inclusión de dichas revisiones. Y el terco es nuestro Blog sobre COVID-19, donde buscamos explicar de manera más ciudadana los resultados que vamos encontrando a medida que se sintetiza la evidencia”, detalla  Sepúlveda. 

Con todo, y pandemia mediante, Epistemonikos sigue cumpliendo sus funciones como asesores para diferentes organizaciones e instituciones del Estado, como, por ejemplo, el Ministerio de Salud -a través de su departamento de síntesis de la evidencia- o el Servicio Nacional del Consumidor; además de alianzas con medios y proyectos de difusión científica y de salud, como saludconLupa.com
